### ISSUE TITLE
MAIN - Section Blocks

### ISSUE THREAD

**Issue by baumannzone** [OSWeekends/osweekends.github.io#12]
# [WEB](https://osw.netlify.com/)

## 👇 Tomar esta imagen como guía 👇 

> Repartiremos las issues según los bloques de la imagen

- Creamos las ramas como `feat/xx`, donde `xx` es el número correspondiente a la issue (en este caso: `feat/12`)
- Al terminar, hacemos PR de nuestra rama `feat/xx` a `new-website`
- Dentro de cada issue, ir creando TO-DO list y marcando (cuando se terminen) las subtareas

![sin titulo-1](https://user-images.githubusercontent.com/5422102/46750419-3466c800-ccb8-11e8-9edf-873e70e76e03.jpg)

**Comment by Josheriff** [comment]
OMG.

Epic
