### ISSUE TITLE
Fix carrusel 

### ISSUE THREAD

**Issue by Jorgeural** [OSWeekends/osweekends.github.io#124]
Volver al carrusel anterior de la parte de los Guilds, poner el logo de OSW menos en aquellos que tengan el suyo propio y reducir las imágenes para que se vean mejor y no queden cortadas

**Comment by baumannzone** [comment]
- Revisar imágenes (ancho y alto)
- Por defecto la imagen de OSW
- Dejar el swiper básico, sin efectos
