### ISSUE TITLE
The link does not work

### ISSUE THREAD

**Issue by abhint** [OSWeekends/osweekends.github.io#137]
https://github.com/OSWeekends/osweekends.github.io/blob/cd6796e68797014eb1b30c0947da0093b55a14be/index.html#L66

**Comment by baumannzone** [comment]
> https://github.com/OSWeekends/osweekends.github.io/blob/cd6796e68797014eb1b30c0947da0093b55a14be/index.html#L66

Actualmente mandamos las invitaciones a mano, debido a los problemas de spam que hemos tenido.

**Comment by abhint** [comment]
Can you invite me? 😄
