### ISSUE TITLE
Resumen Reunión contenidos

### ISSUE THREAD

**Issue by UlisesGascon** [OSWeekends/osweekends.github.io#43]
### Cambios pendientes:
- [x] @baumannzone Meter logo de OSW en el nav-bar
- [x] @baumannzone revisar margenes y paddings con el responsive
- [x] Elementos del menu deben ser iguales que sección 2
- [x] Elementos Sección2 y menú
    - [x] Home (desaparece)
    - [x] Welcome. Textos de @KoolTheba 
    - [x] Guilds. Textos de @KoolTheba 
    - [x] Proyectos. Textos de @KoolTheba 
- [x] Cambiar el orden de las secciones (Guilds x Proyectos)
- [x] Crear un carrusel del Guilds que se pinten en `modo shuffle`
- [x] Generar un JSON con Guilds @KoolTheba (imagen, texto, urls...)
- [x] Generar un JSON con Proyectos @KoolTheba (logos vectoriales, detalles, url, etc...)
- [x] Actualizar el equipo y embajadores (@KoolTheba / @UlisesGascon )
- [ ] Añadir miembros de la comunidad (github) en nueva sección. Generar una tarea de Gulp con un sprite gigante partiendo de la API de Github. @UlisesGascon
- [x] Nueva sección de comunidades hermanadas. Crear JSON @KoolTheba / @UlisesGascon.
- [ ] Generar un sprite de comunidades @UlisesGascon 
- [x] Actualizar patrocinadores y logos con un JSON. @KoolTheba 
- [x] @baumannzone anuncio de cookies
- [x] @baumannzone anuncios en forma de Notificación
- [x] Actualizar sección team @baumannzone 
- [x] Actualizar sección patrocinadores @baumannzone

**Comment by baumannzone** [comment]
@KoolTheba @UlisesGascon ¿esto qué significa?

>  Elementos del menu deben ser iguales que sección 2

**Comment by UlisesGascon** [comment]
- Los títulos de los links del menú deben corresponder con los bloques de la sección 2, verdad @KoolTheba ?
- shuffle sería sacar `n` elementos random de la lista, [idea](https://stackoverflow.com/questions/2450954/how-to-randomize-shuffle-a-javascript-array)

**Comment by baumannzone** [comment]
> @KoolTheba @UlisesGascon ¿esto qué significa?
> 
> * Elementos del menu deben ser iguales que sección 2
> * Qué es modo `shuffle`?

Vale, ya está entendido. 👌

**Comment by UlisesGascon** [comment]
liquidados los JSONs en el #51. El de Usuarios de github tardo un poco más...

**Comment by baumannzone** [comment]
@UlisesGascon queda solo tu parte, si te parece la puedes cerrar
