### ISSUE TITLE
Textos sección 2

### ISSUE THREAD

**Issue by KoolTheba** [OSWeekends/osweekends.github.io#56]
Ref. issue #43 

 ### Welcome

Open Source Weekends somos una comunidad que trabajamos en proyectos y construimos tecnología Open Source, y vamos más allá de dar charlas o hacer workshops. Nos reunimos un sábado al mes y todos los perfiles y niveles de conocimiento son bienvenidos. Lo que está por encima de todo son las ganas de aprender y de compartir lo que sabemos. 
Para que conocer todo lo que hacemos, hemos creado nuestra guía Welcome. Y cualquier pregunta que tengas, ¡contáctanos por Slack o vente a nuestro próximo evento!  

 ### Guilds

OSW es una organización que quiere hacer realidad proyectos Open Source de todo tipo con personas del mundo de la tecnología y otras áreas. Para ello fomentamos la creación de Guilds, que son equipos especializados y multi disciplinares que trabajan desarrollando proyectos para fomentar la Cultura Libre y FOSS. 
Queremos hacer que todo el mundo acceda más fácilmente a la comunidad Open Source y hacer posible que los contributors de hoy sean los líderes del futuro.
Contribuir está al alcance de todo el mundo y no siempre tiene que ser a través de código. Existen muchas formas de contribuir, ¡encuentra la tuya!.

 ### Proyectos

Un proyecto es la puesta en marcha de una idea sobre la que trabaja un Guild. 
Abarcamos áreas en el que el soporte de la tecnología y el Open Source es indispensable. Queremos aportar más valor a la sociedad. La mejor oportunidad es promocionar y cuidar los Guilds y que surjan más ideas que se convierten en proyectos hacia sectores como la Educación, Sanidad, Blockchain, Software y Hardware libre, Legal, Calidad de Empleo, Medio Ambiente, etc. 
OSW pone a la disposición de los Guilds repositorios, subdominios, cloud, formación, mentoría...y muchos recursos más!

**Comment by KoolTheba** [comment]
@UlisesGascon @baumannzone !! Textos hechos! 
Please review: 1) Cantidad de texto (necesitamos más) 2) Calidad de los contenidos (añadiríais algo más??)

**Comment by baumannzone** [comment]
Por mi es OK. 
Lo vamos puliendo más adelante si hace falta. Ya lo he cambiado.

**Comment by baumannzone** [comment]
Necesito saber que "iconos" asignamos a cada bloque:
![image](https://user-images.githubusercontent.com/5422102/47489300-8e35c900-d846-11e8-9fa9-c1f87d8ca4f2.png)


¿Os parecen bien estos? @KoolTheba @Jorgeural @UlisesGascon @NachoRV ?? 🤔
