### ISSUE TITLE
Llamadas AJAX con CORS!

### ISSUE THREAD

**Issue by UlisesGascon** [OSWeekends/osweekends.github.io#76]
Hola gente!

Github habilitó por defecto el uso de CORS con githubraw, por lo que ya podemos olvidarnos de lso estáticos y tirar de nuestros propios JSONs que se actualizan en un único punto :-)

**Fuentes de datos**
- [Data Guilds](https://raw.githubusercontent.com/OSWeekends/Organizacion/master/data/guilds.json)
- [Data Comunidades hermanadas](https://raw.githubusercontent.com/OSWeekends/Organizacion/master/data/communities.json)
- [Data Patrocinadores](https://raw.githubusercontent.com/OSWeekends/Organizacion/master/data/sponsors.json)
- [Data Equipo](https://raw.githubusercontent.com/OSWeekends/Organizacion/master/data/team.json)

**Ejemplo**
```js
fetch("https://raw.githubusercontent.com/OSWeekends/Organizacion/master/data/guilds.json")
  .then((response) => {
    return response.json();
  })
  .then(console.table)
```

**Comment by baumannzone** [comment]
¿Esto va a ser nuestra nueva API? 👎 :trollface:

**Comment by UlisesGascon** [comment]
ahahhaahah.... solo temporalmente... luego moveremos eso a `vanity.osweekends.com/api/v1/<endpoint>` pero para no bloquear..xD

**Comment by Jorgeural** [comment]
- [Data Projects](https://raw.githubusercontent.com/OSWeekends/Organizacion/master/data/projects.json)
