### ISSUE TITLE
JSON Proyectos

### ISSUE THREAD

**Issue by baumannzone** [OSWeekends/osweekends.github.io#81]
Necesitamos el JSON de los proyectos.

Por el momento estamos usando esto: https://github.com/OSWeekends/Organizacion/blob/master/data/projects.json

Pero necesitamos que nos confirmes si es válido o si falta algo

**Comment by UlisesGascon** [comment]
he metido la url de ginger code.. que ya esta online! Por mi.. esta perfecto asi :-)
