### ISSUE TITLE
Tareas 20 Nov 2018

### ISSUE THREAD

**Issue by baumannzone** [OSWeekends/osweekends.github.io#88]
Revisar tareas que faltan.

**Comment by Jorgeural** [comment]
Este comentario lo voy a ir editando con todo lo que vea que hay que retocar / cambiar

- Estilos scrollbar
- Animaciones
- Forma / colores / hover effects / de los botones 
- Quitar CookieConsent
- Hacer componente Cookies (He empezado con ello)
- Botones de navegación
- Mejorar footer
- Testing

**Comment by NachoRV** [comment]
> Este comentario lo voy a ir editando con todo lo que vea que hay que retocar / cambiar
> 
> * Estilos scrollbar (Ya modificado, confirmar que está bien, o sugerir nuevo)
> * Animaciones
> * Forma / colores / hover effects / de los botones
> * Quitar CookieConsent (quitado)
> * Hacer componente Cookies (Solo faltaría animación)
> * Botones de navegación
> * Mejorar footer
> * Testing
> * Accesibilidad
> * Titles / alts
> * **Tarea  ajena a nosotros** Para no depender de las fotos de local, ni de otras fuentes externas, molaría que las fotos "oficiales" estén subidas a algún sitio centralizado de OSW (ya sea un drive, one, imgur o lo que sea) actualizar los datos de los maestros que cojemos y utilizar fotos sin depender de local
> * Una vez finalizado el MVP. Mergear con mastes, y dejar una rama dev para seguir trabajando

* Swiper de guild
